const random: string[] = [
    'The Last Airbender', 
    'waterbending', 
    'earthbending',
    'firebending',
    'airbending',
    'Hundred Year War',
    'Fire Nation','Avatar Roku',
    'all four elements',
    'when the world needed him most',
    'the Water Tribes',
    'Air Nomads',
    'Foggy Swamp',
    'Southern Water Tribe',
    'Northern Water Tribe',
    'Day of Black Sun',
    'Harmonic Convergence',
    'the era of Raava',
    '"I’m angry at myself!"',
    '“It’s the quenchiest!”',
    '“My first girlfriend turned into the moon.”',
    '"That\'s rough, buddy"',
    'Little Soldier Boy',
    'Leaves on the Vine',
    'yip-yip',
    'avatar state',
    'spirit world',
    'spirit library',
    'Southern Air Temple',
    'King of Omashu',
    'Waterbending Scroll',
    'Great Divide',
    'Blue Spirit',
    'Fortuneteller',
    'Bato of the Water Tribe',
    'Deserter',
    'Northern Air Temple',
    'Cave of Two Lovers',
    'Blind Bandit',
    'Avatar Day',
    "The Serpent's Pass",
    'Lake Laogai',
    'Painted Lady',
    'Puppetmaster',
    'Western Air Temple',
    'Boiling Rock',
    'Ember Island Players',
    'The Phoenix King',
    "Sozin's Comet",
    'The Old Masters',
    '"Hahaha, Gravity"',
    'Everything Is Connected',
    'Penguin Sledding',
    'Honor',
    'Space Sword',
    'boomerang', 
    'cactus juice',
    'surf the giant coi-fish',
    'ride the hog-monkeys',
    'blubbered seal jerky',

]
const animals: string[]= [
    'badgermole',
    'Flying bison',
    'Ring-tailed winged lemur',
    'Spiderfly',
    'Winged lemur',
    'Arctic-hippo',
    'Arctic-seal',
    'Cuttlefish ',
    'Dolphinpiranha',
    'Koalaotter',
    'Otterpenguin ',
    'Penguinfish',
    'Puffin-seal sledging',
    'Tigershark',
    'Whale-walrus',
    'Arctic-camel',
    'Arctic-hen',
    'Polarbeardog',
    'Eelhound ',
    'Buzzard-wasp',
    'Hog-monkey',
    'Prickle-snake',
    'Badgerfrog',
    'Dragon',
    'Komodo-rhino',
    'Lion-turtle',
]

const names: string[] = [
    'Aang',
    'Appa',
    'Azula',
    'Iroh',
    'Katara',
    'Momo',
    'Ozai',
    'Sokka',
    'Toph Beifong',
    'Zuko',
    'Yue',
    'Hama',
    'The Boulder',
    'Bumi (King of Omashu)',
    'My Cabbages!',
    'The Dai Li',
    'Flopsie',
    'Jet',
    'Jin Wei',
    'Wei Jin',
    'Suyin Beifong',
    'Long Feng',
    'Lee',
    'Azulon',
    'Combustion Man',
    'the Ember Island Players',
    'Kuzon',
    "Sozin's dragon",
    'Sozin',
    'Roku',
    'Ming-Ming',
    'Gyatso',
    'Yangchen',
    'Lin Beifong',
    'Admiral Zhao',
    'Ba Sing Se', 
    'Kyoshi Warriors',
    'Foofoocuddlypoops',
    'Sparky Sparky Boom Man', 
    'Pathic'
]


export {random, names, animals};